### ISSUE TITLE
Broken bench test

### ISSUE THREAD

**Issue by shanshanzhu** [uber/xviz#337]
On master, run `yarn run bench`, we see failing tests:

```

PARSE XVIZ
├─ xviz#parseMetadata: 248K iterations/s

xviz/src/parsers/parse-xviz-v1.js:328
        vertices[i][2] = zOffset;
        ^
TypeError: Cannot create property '2' on number '3293.046'
    at normalizeXvizPrimitive (xviz/src/parsers/parse-xviz-v1.js:328:9)
    at parseStreamPrimitive (xviz/src/parsers/parse-xviz-v1.js:96:25)
    at xviz/src/parsers/parse-stream-data-message.js:154:31
    at Array.forEach (<anonymous>)
    at parseStateUpdates (xviz/src/parsers/parse-stream-data-message.js:153:6)
    at parseTimesliceData (xviz/src/parsers/parse-stream-data-message.js:120:25)
    at parseStreamLogData (xviz/src/parsers/parse-stream-data-message.js:81:12)
    at xviz/test/bench/xviz.bench.js:16:35
    at runBenchTestIterations (xviz/node_modules/probe.gl/src/bench/bench.js:233:16)
    at runBenchTest (xviz/node_modules/probe.gl/src/bench/bench.js:213:5)
error Command failed with exit code 1.
```

**Comment by shanshanzhu** [comment]
Oops. Sorry, I was on wrong version of xviz. The bench test was broken on internal version, not this one.
