### ISSUE TITLE
validator.validatorMetadata is not a function

### ISSUE THREAD

**Issue by tkt028** [uber/xviz#401]
**Context**
I follow the guideline [1] to validate the generated XVIZ data. My project is using the below package version
  -  "@xviz/builder": "^1.0.0-beta.1",
  -  "@xviz/schema": "^1.0.0-beta.1",

**Problem**
validator.validatorMetadata is not a function (please see below console log).

**Expected**
Able to validate the data according to the guideline [1]

**References**
[1] https://avs.auto/#/xviz/user-guide/validating-xviz

```
$ node
>
>
> xviz_schema = require('@xviz/schema')
{ SCHEMA_DATA: [Getter],
  XVIZValidator: [Getter],
  XVIZSessionValidator: [Getter],
  MessageTypes: [Getter],
  loadProtos: [Getter],
  getXVIZProtoTypes: [Getter],
  EXTENSION_PROPERTY: [Getter],
  protoEnumsToInts: [Getter],
  enumToIntField: [Getter],
  StructEncode: [Getter] }
> validator = new xviz_schema.XVIZValidator();
XVIZValidator {
  ajv:
   Ajv {
     _opts:
      { meta: false,
        schemaId: 'id',
        extendRefs: 'fail',
        loopRequired: Infinity,
        serialize: [Function],
        defaultMeta: 'http://json-schema.org/draft-04/schema#' },
     logger:
      Console {
        log: [Function: bound consoleCall],
        info: [Function: bound consoleCall],
        warn: [Function: bound consoleCall],
        error: [Function: bound consoleCall],
        dir: [Function: bound consoleCall],
        time: [Function: bound consoleCall],
        timeEnd: [Function: bound consoleCall],
        trace: [Function: bound consoleCall],
        assert: [Function: bound consoleCall],
        clear: [Function: bound consoleCall],
        count: [Function: bound consoleCall],
        countReset: [Function: bound countReset],
        group: [Function: bound consoleCall],
        groupCollapsed: [Function: bound consoleCall],
        groupEnd: [Function: bound consoleCall],
        Console: [Function: Console],
        debug: [Function: debug],
        dirxml: [Function: dirxml],
        table: [Function: table],
        markTimeline: [Function: markTimeline],
        profile: [Function: profile],
        profileEnd: [Function: profileEnd],
        timeline: [Function: timeline],
        timelineEnd: [Function: timelineEnd],
        timeStamp: [Function: timeStamp],
        context: [Function: context],
        [Symbol(counts)]: Map {} },
     _schemas:
      { 'http://json-schema.org/draft-04/schema': [Object],
        'envelope.schema.json': [Object],
        'ui-primitives/treetable.schema.json': [Object],
        'style/_color.schema.json': [Object],
        'style/class.schema.json': [Object],
        'style/object_value.schema.json': [Object],
        'style/stream_value.schema.json': [Object],
        'session/camera_info.schema.json': [Object],
        'session/error.schema.json': [Object],
        'session/metadata.schema.json': [Object],
        'session/reconfigure.schema.json': [Object],
        'session/start.schema.json': [Object],
        'session/state_update.schema.json': [Object],
        'session/stream_metadata.schema.json': [Object],
        'session/transform_log.schema.json': [Object],
        'session/transform_log_done.schema.json': [Object],
        'session/transform_point_in_time.schema.json': [Object],
        'session/ui_panel_info.schema.json': [Object],
        'primitives/circle.schema.json': [Object],
        'primitives/image.schema.json': [Object],
        'primitives/point.schema.json': [Object],
        'primitives/polygon.schema.json': [Object],
        'primitives/polyline.schema.json': [Object],
        'primitives/stadium.schema.json': [Object],
        'primitives/text.schema.json': [Object],
        'math/matrix3x3.schema.json': [Object],
        'math/matrix4x4.schema.json': [Object],
        'math/point3d_list.schema.json': [Object],
        'math/vector3x1.schema.json': [Object],
        'declarative-ui/component_base.schema.json': [Object],
        'declarative-ui/panel.schema.json': [Object],
        'declarative-ui/components/_onchange.schema.json': [Object],
        'declarative-ui/components/_tabular.schema.json': [Object],
        'declarative-ui/components/metric.schema.json': [Object],
        'declarative-ui/components/plot.schema.json': [Object],
        'declarative-ui/components/select.schema.json': [Object],
        'declarative-ui/components/table.schema.json': [Object],
        'declarative-ui/components/treetable.schema.json': [Object],
        'declarative-ui/components/video.schema.json': [Object],
        'core/_annotation_list.schema.json': [Object],
        'core/annotation_base.schema.json': [Object],
        'core/annotation_state.schema.json': [Object],
        'core/annotation_visual.schema.json': [Object],
        'core/future_instances.schema.json': [Object],
        'core/pose.schema.json': [Object],
        'core/primitive_base.schema.json': [Object],
        'core/primitive_state.schema.json': [Object],
        'core/stream_set.schema.json': [Object],
        'core/timeseries_state.schema.json': [Object],
        'core/ui_primitive_state.schema.json': [Object],
        'core/value.schema.json': [Object],
        'core/values.schema.json': [Object],
        'core/variable.schema.json': [Object],
        'core/variable_state.schema.json': [Object] },
     _refs:
      { 'http://json-schema.org/draft-04/schema': [Object],
        'https://xviz.org/schema/envelope.json': [Object],
        'https://xviz.org/schema/ui-primitives/treetable.json': [Object],
        'https://xviz.org/schema/style/_color.json': [Object],
        'https://xviz.org/schema/style/class.json': [Object],
        'https://xviz.org/schema/style/object_value.json': [Object],
        'https://xviz.org/schema/style/stream_value.json': [Object],
        'https://xviz.org/schema/session/camera_info.json': [Object],
        'https://xviz.org/schema/session/error.json': [Object],
        'https://xviz.org/schema/session/metadata.json': [Object],
        'https://xviz.org/schema/session/reconfigure.json': [Object],
        'https://xviz.org/schema/session/start.json': [Object],
        'https://xviz.org/schema/session/state_update.json': [Object],
        'https://xviz.org/schema/session/stream_metadata.json': [Object],
        'https://xviz.org/schema/session/transform_log.json': [Object],
        'https://xviz.org/schema/session/transform_log_done.json': [Object],
        'https://xviz.org/schema/session/transform_point_in_time.json': [Object],
        'https://xviz.org/schema/session/ui_panel_info.json': [Object],
        'https://xviz.org/schema/primitives/circle.json': [Object],
        'https://xviz.org/schema/primitives/image.json': [Object],
        'https://xviz.org/schema/primitives/point.json': [Object],
        'https://xviz.org/schema/primitives/polygon.json': [Object],
        'https://xviz.org/schema/primitives/polyline.json': [Object],
        'https://xviz.org/schema/primitives/stadium.json': [Object],
        'https://xviz.org/schema/primitives/text.json': [Object],
        'https://xviz.org/schema/math/matrix3x3.json': [Object],
        'https://xviz.org/schema/math/matrix4x4.json': [Object],
        'https://xviz.org/schema/math/point3d_list.schema.json': [Object],
        'https://xviz.org/schema/math/vector3x1.json': [Object],
        'https://xviz.org/schema/declarative-ui/component_base.json': [Object],
        'https://xviz.org/schema/declarative-ui/panel.json': [Object],
        'https://xviz.org/schema/declarative-ui/components/_onchange.json': [Object],
        'https://xviz.org/schema/declarative-ui/components/_tabular.json': [Object],
        'https://xviz.org/schema/declarative-ui/components/metric.json': [Object],
        'https://xviz.org/schema/declarative-ui/components/plot.json': [Object],
        'https://xviz.org/schema/declarative-ui/components/select.json': [Object],
        'https://xviz.org/schema/declarative-ui/components/table.json': [Object],
        'https://xviz.org/schema/declarative-ui/components/treetable.json': [Object],
        'https://xviz.org/schema/declarative-ui/components/video.json': [Object],
        'https://xviz.org/schema/core/_annotation_list.schema.json': [Object],
        'https://xviz.org/schema/core/annotation_base.json': [Object],
        'https://xviz.org/schema/core/annotation_state.json': [Object],
        'https://xviz.org/schema/core/annotation_visual.json': [Object],
        'https://xviz.org/schema/core/future_instances.json': [Object],
        'https://xviz.org/schema/core/pose.json': [Object],
        'https://xviz.org/schema/core/primitive_base.json': [Object],
        'https://xviz.org/schema/core/primitive_state.json': [Object],
        'https://xviz.org/schema/core/stream_set.json': [Object],
        'https://xviz.org/schema/core/timeseries_state.schema.json': [Object],
        'https://xviz.org/schema/core/ui_primitive_state.json': [Object],
        'https://xviz.org/schema/core/value.schema.json': [Object],
        'https://xviz.org/schema/core/values.schema.json': [Object],
        'https://xviz.org/schema/core/variable.json': [Object],
        'https://xviz.org/schema/core/variable_state.json': [Object] },
     _fragments: {},
     _formats:
      { date: /^\d\d\d\d-[0-1]\d-[0-3]\d$/,
        time: /^(?:[0-2]\d:[0-5]\d:[0-5]\d|23:59:60)(?:\.\d+)?(?:z|[+-]\d\d:\d\d)?$/i,
        'date-time': /^\d\d\d\d-[0-1]\d-[0-3]\d[t\s](?:[0-2]\d:[0-5]\d:[0-5]\d|23:59:60)(?:\.\d+)?(?:z|[+-]\d\d:\d\d)$/i,
        uri: /^(?:[a-z][a-z0-9+-.]*:)(?:\/?\/)?[^\s]*$/i,
        'uri-reference': /^(?:(?:[a-z][a-z0-9+-.]*:)?\/?\/)?(?:[^\\\s#][^\s#]*)?(?:#[^\\\s]*)?$/i,
        'uri-template': /^(?:(?:[^\x00-\x20"'<>%\\^`{|}]|%[0-9a-f]{2})|\{[+#.\/;?&=,!@|]?(?:[a-z0-9_]|%[0-9a-f]{2})+(?::[1-9][0-9]{0,3}|\*)?(?:,(?:[a-z0-9_]|%[0-9a-f]{2})+(?::[1-9][0-9]{0,3}|\*)?)*\})*$/i,
        url: /^(?:(?:http[s\u017F]?|ftp):\/\/)(?:(?:[\0-\x08\x0E-\x1F!-\x9F\xA1-\u167F\u1681-\u1FFF\u200B-\u2027\u202A-\u202E\u2030-\u205E\u2060-\u2FFF\u3001-\uD7FF\uE000-\uFEFE\uFF00-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])+(?::(?:[\0-\x08\x0E-\x1F!-\x9F\xA1-\u167F\u1681-\u1FFF\u200B-\u2027\u202A-\u202E\u2030-\u205E\u2060-\u2FFF\u3001-\uD7FF\uE000-\uFEFE\uFF00-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])*)?@)?(?:(?!10(?:\.[0-9]{1,3}){3})(?!127(?:\.[0-9]{1,3}){3})(?!169\.254(?:\.[0-9]{1,3}){2})(?!192\.168(?:\.[0-9]{1,3}){2})(?!172\.(?:1[6-9]|2[0-9]|3[01])(?:\.[0-9]{1,3}){2})(?:[1-9][0-9]?|1[0-9][0-9]|2[01][0-9]|22[0-3])(?:\.(?:1?[0-9]{1,2}|2[0-4][0-9]|25[0-5])){2}(?:\.(?:[1-9][0-9]?|1[0-9][0-9]|2[0-4][0-9]|25[0-4]))|(?:(?:(?:[0-9KSa-z\xA1-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])+-?)*(?:[0-9KSa-z\xA1-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])+)(?:\.(?:(?:[0-9KSa-z\xA1-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])+-?)*(?:[0-9KSa-z\xA1-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])+)*(?:\.(?:(?:[KSa-z\xA1-\uD7FF\uE000-\uFFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]){2,})))(?::[0-9]{2,5})?(?:\/(?:[\0-\x08\x0E-\x1F!-\x9F\xA1-\u167F\u1681-\u1FFF\u200B-\u2027\u202A-\u202E\u2030-\u205E\u2060-\u2FFF\u3001-\uD7FF\uE000-\uFEFE\uFF00-\uFFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF])*)?$/i,
        email: /^[a-z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)*$/i,
        hostname: /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[-0-9a-z]{0,61}[0-9a-z])?)*$/i,
        ipv4: /^(?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?)$/,
        ipv6: /^\s*(?:(?:(?:[0-9a-f]{1,4}:){7}(?:[0-9a-f]{1,4}|:))|(?:(?:[0-9a-f]{1,4}:){6}(?::[0-9a-f]{1,4}|(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(?:(?:[0-9a-f]{1,4}:){5}(?:(?:(?::[0-9a-f]{1,4}){1,2})|:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(?:(?:[0-9a-f]{1,4}:){4}(?:(?:(?::[0-9a-f]{1,4}){1,3})|(?:(?::[0-9a-f]{1,4})?:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(?:(?:[0-9a-f]{1,4}:){3}(?:(?:(?::[0-9a-f]{1,4}){1,4})|(?:(?::[0-9a-f]{1,4}){0,2}:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(?:(?:[0-9a-f]{1,4}:){2}(?:(?:(?::[0-9a-f]{1,4}){1,5})|(?:(?::[0-9a-f]{1,4}){0,3}:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(?:(?:[0-9a-f]{1,4}:){1}(?:(?:(?::[0-9a-f]{1,4}){1,6})|(?:(?::[0-9a-f]{1,4}){0,4}:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(?::(?:(?:(?::[0-9a-f]{1,4}){1,7})|(?:(?::[0-9a-f]{1,4}){0,5}:(?:(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(?:\.(?:25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(?:%.+)?\s*$/i,
        regex: [Function: regex],
        uuid: /^(?:urn:uuid:)?[0-9a-f]{8}-(?:[0-9a-f]{4}-){3}[0-9a-f]{12}$/i,
        'json-pointer': /^(?:\/(?:[^~\/]|~0|~1)*)*$/,
        'json-pointer-uri-fragment': /^#(?:\/(?:[a-z0-9_\-.!$&'()*+,;:=@]|%[0-9a-f]{2}|~0|~1)*)*$/i,
        'relative-json-pointer': /^(?:0|[1-9][0-9]*)(?:#|(?:\/(?:[^~\/]|~0|~1)*)*)$/ },
     _cache: Cache { _cache: [Object] },
     _loadingSchemas: {},
     _compilations: [],
     RULES:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        all: [Object],
        types: [Object],
        keywords: [Object],
        custom: {} ],
     _getId: [Function: _getId],
     _metaOpts:
      { meta: false,
        schemaId: 'id',
        extendRefs: 'fail',
        loopRequired: Infinity,
        serialize: [Function] },
     errors: null } }
>
>
> metadata = {
...   version: '2.0.0'
... };
{ version: '2.0.0' }
>
> validator.validatorMetadata(metadata);
TypeError: validator.validatorMetadata is not a function
    at repl:1:11
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
>
>
>
```

**Comment by twojtasz** [comment]
This looks like a simple bug, could you try `validateMetadata` instead of `validatorMetadata`. I'll update the docs.

**Comment by twojtasz** [comment]
https://github.com/uber/xviz/commit/aa704096f0d7592d3937fc723418e4eb8fbbadf0

Thank!
