### ISSUE TITLE
can't convert KITTI to XVIZ data

### ISSUE THREAD

**Issue by EliotCao** [uber/xviz#432]
When i try to run XVIZ convert demo, i met the bug 'node-expat command fails when trying to convert KITTI to XVIZ' >  #399

 and last i change xml2json to xml-js, then i recive error info:

(node:16616) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at TrackletsConverter.forEach (C:\Users\rznqgt\Desktop\2\xviz-1.0.0-beta.7\examples\converters\kitti\src\converters/tracklets-converter.js:88:15)
    at tryCatch (C:\Users\rznqgt\Desktop\2\xviz-1.0.0-beta.7\examples\converters\kitti\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\rznqgt\Desktop\2\xviz-1.0.0-beta.7\examples\converters\kitti\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\rznqgt\Desktop\2\xviz-1.0.0-beta.7\examples\converters\kitti\node_modules\regenerator-runtime\runtime.js:117:21)
    at asyncGeneratorStep (C:\Users\rznqgt\Desktop\2\xviz-1.0.0-beta.7\examples\converters\kitti\src\converters\tracklets-converter.js:24:103)
    at _next (C:\Users\rznqgt\Desktop\2\xviz-1.0.0-beta.7\examples\converters\kitti\src\converters\tracklets-converter.js:26:194)
    at C:\Users\rznqgt\Desktop\2\xviz-1.0.0-beta.7\examples\converters\kitti\src\converters\tracklets-converter.js:26:364
    at new Promise (<anonymous>)
    at TrackletsConverter.<anonymous> (C:\Users\rznqgt\Desktop\2\xviz-1.0.0-beta.7\examples\converters\kitti\src\converters\tracklets-converter.js:26:97)
    at TrackletsConverter.convertFrame (C:\Users\rznqgt\Desktop\2\xviz-1.0.0-beta.7\examples\converters\kitti\src\converters\tracklets-converter.js:144:30)
(node:16616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rej
ection id: 2)
(node:16616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 8.73s.

**Comment by zied1A** [comment]
Hi , did you find a solution for this issue ?

**Comment by EliotCao** [comment]
> Hi , did you find a solution for this issue ?
pls reference: https://github.com/uber/xviz/issues/399#issuecomment-489401641
