### ISSUE TITLE
Fail to convert KITTI data using example script

### ISSUE THREAD

**Issue by hefc2016** [uber/xviz#572]
Hello 

I'm studying to use xviz and follow the quick start guideline. When I run below script ./scripts/run-kitti-example.sh, I have below error come out. I try to rebuild the node-expat using `npm rebuild` or `npm install` according to error indication, but this error still not fixed.

some info of my environment:
- node - v11.15.0
- npm - 6.13.7
- yarn - 1.21.1
- Linux - Ubuntu 16.04 LTS in WIN10 as subsystem

Can anyone help give suggestion to me?
Appreciate.

Error: The module '/home/hefc/GIT/xviz/examples/converters/kitti/node_modules/node-expat/build/Release/node_expat.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 67. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:857:18)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (/home/hefc/GIT/xviz/examples/converters/kitti/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/home/hefc/GIT/xviz/examples/converters/kitti/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Module._compile (/home/hefc/GIT/xviz/examples/converters/kitti/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:827:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hefc2016** [comment]
I use `npm rebuild node-expat --update-binary` to rebuild node-expat and then this issue fixed.
